Parameters:
  ProjectName:
    Type: String
    Default: as-tours
  WebsiteBucketName:
    Type: String
    Default: as-tours-website
  RDSDBName:
    Description: "RDS database name. Must begin with a letter, contain only letters and numbers, no hyphens and/or underscores, and be no longer than 63 characters."
    Type: String
    Default: anothersidetoursdb
  DBSecretName:
    Type: String
    Default: as-tours-rds-secret
  DBUsername:
    Type: String
    Default: 
  FrontendRepositoryBranch:
    Type: String
    Default: main
  BackendRepositoryBranch:
    Type: String
    Default: master
  GitHubv2ConnectionArn:
    Type: String
    Default: 
  GitHubOwner:
    Type: String
    Default: tmaior
  FrontendGitHubRepo:
    Type: String
    Default: Anothersidetours-frontend
  BackendGitHubRepo:
    Type: String
    Default: anothersidetours-backend
  BuildSpecPath:
    Type: String
    Default: devops/buildspec.yaml
  ACMCertificateArn:
    Type: String
    Default:
    Description: ARN of the SSL/TLS certificate used to enable HTTPS on the ALB
  KeyName:
    Type: String
    Default: 
    Description: indicate the key pair name for your EC2 instances
  EcsImage:
    Type: String
    Default: 
    Description: run the command and use the ami id (change the AWS region) #aws ssm get-parameters --names /aws/service/ecs/optimized-ami/amazon-linux-2/recommended --region us-east-2
  
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://anothersidetours-infrastructure-templates.s3.us-east-2.amazonaws.com/vpc.yaml
      Parameters:
        ProjectName: !Ref ProjectName
  
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://anothersidetours-infrastructure-templates.s3.us-east-2.amazonaws.com/rds.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        DBSecretName: !Ref DBSecretName
        DBUsername: !Ref DBUsername
        DBName: !Ref RDSDBName

  CICDStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://anothersidetours-infrastructure-templates.s3.us-east-2.amazonaws.com/cicd.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        FrontendRepositoryBranch: !Ref FrontendRepositoryBranch
        BackendRepositoryBranch: !Ref BackendRepositoryBranch
        GitHubv2ConnectionArn: !Ref GitHubv2ConnectionArn
        GitHubOwner: !Ref GitHubOwner
        FrontendGitHubRepo: !Ref FrontendGitHubRepo
        BackendGitHubRepo: !Ref BackendGitHubRepo
        BuildSpecPath: !Ref BuildSpecPath
        WebsiteS3Bucket: !Ref WebsiteBucketName

  S3CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CICDStack
    Properties:
      TemplateURL: https://anothersidetours-infrastructure-templates.s3.us-east-2.amazonaws.com/s3-cloudfront.yaml
      Parameters:
        WebsiteBucketName: !Ref WebsiteBucketName
        CodeBuildServiceRole: !GetAtt CICDStack.Outputs.CodeBuildRoleArn
  
  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://anothersidetours-infrastructure-templates.s3.us-east-2.amazonaws.com/alb.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        ACMCertificateArn: !Ref ACMCertificateArn

  ASGStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBStack
    Properties:
      TemplateURL: https://anothersidetours-infrastructure-templates.s3.us-east-2.amazonaws.com/asg.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EcsImage: !Ref EcsImage 
        AsgServiceMax: 2
        AsgServiceMin: 1
        AsgServiceDesired: 1
        KeyName: !Ref KeyName 
        ECSInstanceType: t3.medium
        BastionInstanceType: t3.micro

  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [RDSStack, ALBStack]
    Properties:
      TemplateURL: https://anothersidetours-infrastructure-templates.s3.us-east-2.amazonaws.com/ecs.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        DBEndpoint: !GetAtt RDSStack.Outputs.RDSHost
        DBUsername: !Ref DBUsername
        DBName: !Ref RDSDBName
        DBSecretName: !Ref DBSecretName
